export default (router) => a['app-test-report']([
  a.h1('Report'),
  x.report({
    shims: [
      x.report.field.shim,
      x.report.field.extras.shim,
      x.report.field.dependent.shim,
      x.report.field.nest.shim,
      x.report.field.nest.prefab.shim,
      x.bootstrap.report.shim,
      x.xtermjs.report.shim,
      x.codemirror.report.shim,
    ],
    horizontal: true,
    object: {
      checkbox: 'something truthy',
      checkboxes: ['beta','gamma'],
      hidden: 'no see',
      output1: 'Text\noutput',
      output2: 20,
      output3: {one:1, two:2, three:3},
      radios: 'beta',
      select: 'beta',
      string: 'Single-line text.',
      text: 'Multi-line\ntext\nMulti-line\ntext\nMulti-line\ntext\nMulti-line\ntext\nMulti-line\ntext\nMulti-line\ntext\nMulti-line\ntext',

      boolean: 'something truthy',
      color: '#4488DD',
      country: 'AU',
      datetime: 'October 13, 2014 11:13:00',
      email: 'mail@example.com',
      json: '{"one": 1}',
      language: 'EN',
      number: 10,
      password: 'mysecret1',
      preformatted: 'N N N\nM M M\n1 1 1\n0 0 0',
      tel: '12223334444',
      timezone: 'Australia/Sydney',
      url: 'http://www.example.com',
      terminal: 'Hello from \x1B[1;3;31mxterm.js\x1B[0m\r\n',
      code: 'let n = 1;',
      code_mode: 'javascript',
      // markdown: 'This is **markdown**.',
    },
    report: (r) => [
      r.field({key: 'checkbox', as: 'checkbox', control: {label: 'Check me'}}),
      r.field({key: 'checkboxes', as: 'checkboxes', selections: {alpha: 'Alpha', beta: 'Beta', gamma: 'Gamma', delta: 'Delta'}}),
      r.field({key: 'hidden', as: 'hidden'}),
      r.field({key: 'radios', as: 'radios', selections: {alpha: 'Alpha', beta: 'Beta', gamma: 'Gamma', delta: 'Delta'}}),
      r.field({key: 'select', as: 'select', selections: {alpha: 'Alpha', beta: 'Beta', gamma: 'Gamma', delta: 'Delta'}}),
      r.field({key: 'string', as: 'string', help: 'This is help.'}),
      r.field({key: 'text', as: 'text', resize: '100-200'}),
      r.field({key: 'boolean', as: 'boolean'}),
      r.field({key: 'color', as: 'color'}),
      r.field({key: 'country', as: 'country'}),
      r.field({key: 'email', as: 'email'}),
      r.field({key: 'json', as: 'json', parse: true}),
      r.field({key: 'language', as: 'language'}),
      r.field({key: 'number', as: 'number'}),
      r.field({key: 'password', as: 'password'}),
      r.field({key: 'preformatted', as: 'preformatted'}),
      r.field({key: 'tel', as: 'tel'}),
      r.field({key: 'url', as: 'url'}),
      r.field({
        key: 'terminal',
        as: 'xtermjs',
        // toolbar: false,
        divTag: {style: {height: '100px'}},
        control: {
          label: 'Gday Gday',
        },
      }),
      r.field({
        key: 'code',
        as: 'codemirror',
        mode: 'javascript',
        keymap: true,
        lineNumbers: false,
        control: {
          label: 'Gday Gday  Gday Gday Gday Gday Gday Gday ',
        },
      }),

      r.field({key: 'output1', as: 'output'}),
      r.field({key: 'output2', as: 'output'}),
      r.field({key: 'output3', as: 'output'}),
      r.field({key: 'output4', as: 'output', value: r.object}),
    ],
  }),
])
